CTCTRADERS-2848: testOnly route to drop mongo collection.
hmrc/transit-movements-guarantee-balance pull request #26
Opened 2021-12-09 15:15 UTC by jackheslop96

2021-12-09 17:53 UTC, DavidGregory084 requested changes

2021-12-09 17:53 UTC, DavidGregory084 commented on conf/application.conf
> +play.modules.enabled += "play.modules.reactivemongo.ReactiveMongoModule"
Please do not do this - this service uses hmrc-mongo because reactivemongo is deprecated

2021-12-09 17:53 UTC, DavidGregory084 commented on project/AppDependencies.scala
> +    "org.reactivemongo"      %% "play2-reactivemongo"       % "0.20.13-play28",
Please do not do this - this service uses hmrc-mongo because reactivemongo is deprecated

2021-12-09 17:53 UTC, DavidGregory084 commented on app/controllers/testOnly/TestOnlyMongoController.scala
> +  }
I think the best way to do this in hmrc-mongo is to inject the `PlayMongoComponent` and use the `database` that it provides - see e.g. http://mongodb.github.io/mongo-java-driver/4.2/driver-scala/tutorials/databases-collections/#drop-a-collection

2021-12-09 17:55 UTC, DavidGregory084 commented on conf/testOnlyDoNotUseInAppConf.routes
> +DELETE     /transit-movements-guarantee-balance/test-only/drop-mongo-collection       controllers.testOnly.TestOnlyMongoController.dropMongoCollection()
Very small thing, but would it be possible to change this route to `/transit-movements-guarantee-balance/test-only/balances`?
I think the intent to drop the collection is already clear from the `DELETE` method, and this endpoint operates on balance requests.

2021-12-09 17:57 UTC, DavidGregory084 commented on app/controllers/testOnly/TestOnlyMongoController.scala
> +  }
Oh and https://github.com/hmrc/hmrc-mongo/blob/main/hmrc-mongo-common/src/main/scala/uk/gov/hmrc/mongo/MongoComponent.scala

2021-12-09 18:24 UTC, DavidGregory084 commented on app/controllers/testOnly/TestOnlyMongoController.scala
> +  override val messagesApi: MessagesApi,
Is this `override` needed?

2021-12-10 14:54 UTC, jackheslop96 commented
@DavidGregory084 thank you for reviewing this yesterday evening it's very much appreciated and the comments were extremely insightful. I had been lazy and just copied some code from transit-movements-trader-at-destination. I hope my latest commit has addressed all of your comments - if there are any further issues let me know :)

2021-12-10 17:27 UTC, DavidGregory084 approved these changes
Yep looks good to me! 💯

2021-12-13 10:23 UTC, merged